# Generated by Django 2.2.12 on 2020-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('Empname', models.CharField(max_length=100)),
                ('Desig', models.CharField(max_length=100)),
                ('Emppic', models.FileField(upload_to='')),
                ('Empsal', models.IntegerField()),
                ('Dob', models.DateField()),
                ('Joind', models.DateField()),
            ],
        ),
    ]
